### PR TITLE
Don't crash if ical does not have summary or description fixes #576

### LINKED ISSUE #576: NoMethodError in radar:fetch
## Exception in Hacken.in

**NoMethodError** in **radar:fetch**
undefined method &#x60;force_encoding&#x27; for nil:NilClass

[View on Bugsnag](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/552408f0cf825b739dc0f813?event_id=5526abf3d8c63a2d3d7856c7)

## Stacktrace

    lib/radar/ical.rb:21 - parse_event
    lib/radar/ical.rb:12 - block in next_events
    lib/radar/ical.rb:11 - map
    lib/radar/ical.rb:11 - next_events
    lib/radar/base.rb:13 - fetch
    app/models/radar_setting.rb:6 - fetch
    lib/tasks/radar.rake:6 - block (3 levels) in &lt;top (required)&gt;
    lib/tasks/radar.rake:5 - block (2 levels) in &lt;top (required)&gt;

[View full stacktrace](https://bugsnag.com/hacken-dot-in/hacken-dot-in/errors/552408f0cf825b739dc0f813?event_id=5526abf3d8c63a2d3d7856c7)

### PR DESCRIPTION
**Pull request by bitboxer**

### CODE REVIEW

**Comment by bascht** [comment]
whoops. :)

File: lib/radar/ical.rb [hunk 1]
```diff
@@ -17,8 +17,8 @@ def parse_event(event)
       result = {
         id: event.start.to_s,
         url: event.url.to_s,
-        title: event.summary.force_encoding("utf-8"),
-        description: event.description.force_encoding("utf-8"),
+        title: (event.summary || "").force_encoding("utf-8"),
```
Comment (bascht) [inline lib/radar/ical.rb]: Is it nil or undefined? (If nil, then `event.summary.to_s.force_encoding` would do the same, no?

Comment (bitboxer) [inline lib/radar/ical.rb]: Yes, it is nil. `.to_s` will do the same. But I love to write it this way to make it clear. Otherwise I don't know why it is there and remove it :wink:

Comment (bascht) [inline lib/radar/ical.rb]: Makes sense. :+1:
